package itfy::Model::ItfyDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'itfy::Schema::ItfyDB',
    
    
);

=head1 NAME

itfy::Model::ItfyDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<itfy>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<ItfyDB::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.43

=head1 AUTHOR

A clever guy

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
